fix(workflows): removing dependency

diff --git a/.github/workflows/pre-release-python-bridge.yml b/.github/workflows/pre-release-python-bridge.yml
--- a/.github/workflows/pre-release-python-bridge.yml
+++ b/.github/workflows/pre-release-python-bridge.yml
@@ -72,117 +72,117 @@ jobs:
         with:
           path: bridges/python/dist/*.zip
 
-  build-linux-ARM64:
-    name: Build Linux AARCH64
-    permissions:
-      packages: write
-      contents: write
+  # build-linux-ARM64:
+  #   name: Build Linux AARCH64
+  #   permissions:
+  #     packages: write
+  #     contents: write
 
-    strategy:
-      fail-fast: false
+  #   strategy:
+  #     fail-fast: false
 
-    runs-on: [self-hosted, linux-latest, ARM64]
-    timeout-minutes: 15
+  #   runs-on: [self-hosted, linux-latest, ARM64]
+  #   timeout-minutes: 15
 
-    steps:
-      - name: Clone repository
-        uses: actions/checkout@v3
-        with:
-          repository: ${{ env.REPOSITORY_NAME }}
-          ref: refs/heads/${{ github.event.inputs.branch }}
-          token: ${{ secrets.GH_PAT }}
+  #   steps:
+  #     - name: Clone repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: ${{ env.REPOSITORY_NAME }}
+  #         ref: refs/heads/${{ github.event.inputs.branch }}
+  #         token: ${{ secrets.GH_PAT }}
 
-      - name: Install Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9.10
+  #     - name: Install Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: 3.9.10
 
-      - name: Install Pipenv
-        run: pip install --upgrade pip && pip install pipenv==2022.7.24
+  #     - name: Install Pipenv
+  #       run: pip install --upgrade pip && pip install pipenv==2022.7.24
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: lts/*
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: lts/*
 
-      - name: Set Python bridge version
-        working-directory: bridges/python/src
-        run: |
-          echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV
+  #     - name: Set Python bridge version
+  #       working-directory: bridges/python/src
+  #       run: |
+  #         echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV
 
-      - name: Display Python bridge version
-        run: |
-          echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"
+  #     - name: Display Python bridge version
+  #       run: |
+  #         echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"
 
-      - name: Install core
-        run: npm install || true
+  #     - name: Install core
+  #       run: npm install || true
 
-      - name: Set up Python bridge
-        run: npm run setup:python-bridge
+  #     - name: Set up Python bridge
+  #       run: npm run setup:python-bridge
 
-      - name: Build Python bridge
-        run: npm run build:python-bridge
+  #     - name: Build Python bridge
+  #       run: npm run build:python-bridge
 
-      - name: Upload Python bridge
-        uses: actions/upload-artifact@v3
-        with:
-          path: bridges/python/dist/*.zip
+  #     - name: Upload Python bridge
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         path: bridges/python/dist/*.zip
 
-  build-macos-ARM64:
-    name: Build macOS AARCH64
-    permissions:
-      packages: write
-      contents: write
+  # build-macos-ARM64:
+  #   name: Build macOS AARCH64
+  #   permissions:
+  #     packages: write
+  #     contents: write
 
-    strategy:
-      fail-fast: false
+  #   strategy:
+  #     fail-fast: false
 
-    runs-on: [self-hosted, macos-latest, ARM64]
-    timeout-minutes: 15
+  #   runs-on: [self-hosted, macos-latest, ARM64]
+  #   timeout-minutes: 15
 
-    steps:
-      - name: Clone repository
-        uses: actions/checkout@v3
-        with:
-          repository: ${{ env.REPOSITORY_NAME }}
-          ref: refs/heads/${{ github.event.inputs.branch }}
-          token: ${{ secrets.GH_PAT }}
+  #   steps:
+  #     - name: Clone repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: ${{ env.REPOSITORY_NAME }}
+  #         ref: refs/heads/${{ github.event.inputs.branch }}
+  #         token: ${{ secrets.GH_PAT }}
 
-      - name: Install Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9.10
+  #     - name: Install Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: 3.9.10
 
-      - name: Install Pipenv
-        run: pip install --upgrade pip && pip install pipenv==2022.7.24
+  #     - name: Install Pipenv
+  #       run: pip install --upgrade pip && pip install pipenv==2022.7.24
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: lts/*
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: lts/*
 
-      - name: Set Python bridge version
-        working-directory: bridges/python/src
-        run: |
-          echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV
+  #     - name: Set Python bridge version
+  #       working-directory: bridges/python/src
+  #       run: |
+  #         echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV
 
-      - name: Display Python bridge version
-        run: |
-          echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"
+  #     - name: Display Python bridge version
+  #       run: |
+  #         echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"
 
-      - name: Install core
-        run: npm install || true
+  #     - name: Install core
+  #       run: npm install || true
 
-      - name: Set up Python bridge
-        run: npm run setup:python-bridge
+  #     - name: Set up Python bridge
+  #       run: npm run setup:python-bridge
 
-      - name: Build Python bridge
-        run: npm run build:python-bridge
+  #     - name: Build Python bridge
+  #       run: npm run build:python-bridge
 
-      - name: Upload Python bridge
-        uses: actions/upload-artifact@v3
-        with:
-          path: bridges/python/dist/*.zip
+  #     - name: Upload Python bridge
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         path: bridges/python/dist/*.zip
           
   draft-release:
     name: Draft-release
